# Generated by Django 4.2.7 on 2023-12-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='test1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
